### ISSUE TITLE
Can not make it work, keeps giving this error message.

### ISSUE THREAD

**Issue by anarpcg** [JBGruber/askgpt#3]
remotes::install_github("JBGruber/askgpt")
#rappdirs::user_cache_dir("askgpt")
#login(force_refresh = TRUE)
library(askgpt)
askgpt("Can you explain how functions work in R?")

Error:is thinking \
! ! in callr subprocess.
Caused by error: 
! Timeout was reached: [api.openai.com] Connection timeout after 10010 ms
Backtrace:
 1. askgpt::askgpt("Can you explain how functions work in R?")
 2. rp$get_result()
 3. callr:::rp_get_result(self, private)
 4. callr:::get_result(out, private$options)
 5. throw(callr_remote_error(remerr, output), parent = fix_msg(remerr[[3]]))
x GPT is thinking \ [12.5s]

**Comment by JBGruber** [comment]
Could you try this:

```
library(askgpt)
askgpt("Can you explain how functions work in R?", progress = FALSE)
```

I haven't seen a timeout yet. AFAIK it could either mean that you have a week internet connection and the API can´t be reached or that something weird is happening with `callr`, which is used for the "thinking" animation. Setting `progress = FALSE` disables the animation.

**Comment by JBGruber** [comment]
Closing this, since I haven't heard back and can't reproduce.
