### ISSUE TITLE
HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by jhebenstreit** [JBGruber/askgpt#5]
Hi,

if I run the command:
askgpt("What is an R function?")

I get the following error messages:
Error:is thinking ⠇
! ! in callr subprocess.
Caused by error in `resp_abort(resp, error_body(req, resp))`:
! HTTP 401 Unauthorized.
Run `rlang::last_error()` to see where the error occurred.
✖ GPT is thinking ⠇ [1.6s]

I partly understand the problem but I do not know how to solve it in R. Btw I have full administrative rights on the PC and a working internet connection. Using ChatGPT in the explorer works fine as well.

Many thanks in advance!
Jörg

**Comment by jhebenstreit** [comment]
Update: I needed to install the keyring package as well. Now it works fine!

**Comment by JBGruber** [comment]
Ah thanks for the update! What OS are you on (for future reference).
