### ISSUE TITLE
Error running askgpt

### ISSUE THREAD

**Issue by ManuelSpinola** [JBGruber/askgpt#6]
I got an error when I try to use askgpt:

library(askgpt)
log_init()
askgpt("what is an R function")
Error:is thinking ⠦
! ! in callr subprocess.
Caused by error in `resp_abort(resp, error_body(req, resp))`:
! HTTP 429 Too Many Requests.
Run `rlang::last_trace()` to see where the error occurred.
✖ GPT is thinking ⠦ [3.1s]

**Comment by ingorohlfing** [comment]
I have the same problem when trying to run any {askgpt} function. It is the same problem on two different devives (both Windows 10, R 4.2.3, current RStudio version) that I set up for use as recommended, I think. When I use ChatGPT online, it works fine, so it does not seem to be a problem with ChatGPT being unavailable.

**Comment by JBGruber** [comment]
API requests run through a different billing 'account'. The error likely means that you have no credit left for API requests and no credit card on that 'account'. At least that was the case for me, even though I'm paying for a Plus account and OpenAI had my credit card already. You can check that here: <https://platform.openai.com/account/usage>

You get more than enough credit when you first sign on (no matter if free or plus tier), but the credit expires after 3 months (I discovered this only when it happened to me). API requests are very cheap, so I don't mind paying for them (it was about 0.50$ for 100s of requests in April), but it's up to you if you want to give OpenAI your credit card information...

**Comment by ingorohlfing** [comment]
Thanks, this makes sense. I will look into this.
