### ISSUE TITLE
Trying to annotate selected code

### ISSUE THREAD

**Issue by JW-spec-tech** [JBGruber/askgpt#8]
Getting the following output:

askgpt::annotate_code()
✔ GPT is thinking ⠧ [9.2s]
Warning message:
In file(loc, "ab") :
  file("") only supports open = "w+" and open = "w+b": using the former
  
  I am running on rstudio server

**Comment by JBGruber** [comment]
Thanks for making me aware of this! It seems like the addin is only working with named files. `file("")` shows me that the file you are trying to change (by adding annotations) is "" (so nothing) which does not work. 

I will try to write a clear error or warning message as I don't know how to work around that.
